# Generated by Django 4.1.3 on 2022-11-07 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='thunbnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
