# Generated by Django 4.1.3 on 2022-11-07 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_blogpost_thunbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='thunbnail',
            field=models.ImageField(blank=True, default=1, upload_to='blog'),
            preserve_default=False,
        ),
    ]
