# Generated by Django 4.1.3 on 2022-11-07 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_blogpost_thunbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='thunbnail',
            new_name='thumbnail',
        ),
    ]
